name: Cypress Tests

on:
  deployment_status:

  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci && npx cypress install
    - name: Run Tests
        run: npx cypress test
          env:
              BASE_URL: ${{ github.event.deployment_status.target_url }}
