name: cypress-test-on-vercel-preview

on: [push, deployment, deployment_status]

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: dump-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: install-dependencies
        run: npm install --loglevel verbose
      - name: run-tests
        run: npm run cypress-test-on-vercel-preview
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
